name: sample-web-application

on:
  push:
    branches:
      - ansible-sonar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Use the latest version of the checkout action

      - name: Build and Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          DOCKER_BUILDKIT=0 docker build -t my-sample-app .
          docker tag my-sample-app:latest your-dockerhub-username/my-sample-app:latest
          docker push your-dockerhub-username/my-sample-app:latest

