name: sample-web-application

on:
  push:
    branches:
    - ansible-sonar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy  to Docker
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        # Build and deploy the Docker container
        docker build -t my-sample-app .
        docker tag my-sample-app:latest javeriakashan/my-sample-app:latest
        docker push javeriakashan/my-sample-app:latest
